pipeline {
   agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
       
       stage('Deploy'){
          steps{
             
             bat '''copy C:\\Users\\Mayuresh.Marathe\\.jenkins\workspace\\SampleMavenApp\\target\\*.jar '''
          }
       }
    }
}
